version = 1

[enemy]
id = "hopper_basic"
display = "Hopper"
type = "hopper"

[collision]
w = 24
h = 22

[move]
speed = 0.4
gravity = 0.2
max_fall_speed = 4.0
turn_on_wall = true
turn_on_edge = true

[combat]
health = 1
contact_damage = 1
stompable = true
stomp_bounce_vy = -4.0
iframes_ms = 250
knockback_vx = 1.5
knockback_vy = -2.5

[hopper]
interval_frames = 60
hop_speed_x = 0.9
hop_speed_y = -4.2
