version = 1
include = [
  "../../characters/_includes/form_anchor_ninja.toml",
  "../../characters/_includes/render_sonic_placeholder.toml",
  "../../characters/_includes/physics_ninja.toml",
  "../../characters/_includes/move_ninja.toml",
  "../../characters/_includes/math_pixel_trunc_256.toml",
  "../../characters/_includes/jump_ninja_impulse_3_83.toml",
  "../../characters/_includes/actions_dash_ninja.toml",
]

[name]
id = "ninja_airdash"
display = "Ninja (Air Dash)"

[form]
id = "puppet"
palette_base = "2C2C2C"
palette_accent = "8B0000"
variants = ["ninja"]

[form.colors]
mask = "2C2C2C"
headband = "8B0000"
weapon = "C0C0C0"
glove = "2C2C2C"
shoe = "2C2C2C"

[actions.spin]
enabled = false

[actions.fly]
enabled = false

[actions.glide]
enabled = false

[actions.spindash]
enabled = false
