version = 1
include = [
  "../../characters/_includes/form_colors_glove_shoe_brown.toml",
  "../../characters/_includes/render_mario_placeholder.toml",
  "../../characters/_includes/physics_mario.toml",
  "../../characters/_includes/move_mario.toml",
  "../../characters/_includes/math_pixel_trunc_16.toml",
  "../../characters/_includes/jump_mario_dual_gravity.toml",
]

[name]
id = "test_jump_table"
display = "Mario (Jump Table)"

[form]
id = "puppet"

[move]
model = "instant"

[[jump.impulse_by_speed]]
min_abs_vx = 0.0
impulse = 3.67

[[jump.impulse_by_speed]]
min_abs_vx = 1.67
impulse = 4

[actions.spin]
enabled = false

[actions.dash]
enabled = false

[actions.fly]
enabled = false

[actions.glide]
enabled = false

[actions.spindash]
enabled = false
type = "hold"
charge_frames = 55
min_launch_speed = 2
max_launch_speed = 5.42
