version = 1
include = [
  "../../characters/_includes/form_colors_glove_shoe_charcoal.toml",
  "../../characters/_includes/render_sonic_placeholder.toml",
  "../../characters/_includes/math_pixel_trunc_256.toml",
  "../../characters/_includes/jump_sonic_impulse_4.toml",
]

[name]
id = "test_air_drag"
display = "Air Drag Zone"

[form]
id = "puppet"

[physics]
gravity = 0.166667
max_fall_speed = 18.33
ground_friction = 5.0
air_drag = 0.4

[move]
model = "approach"
air_control = true
accel_ground = 0.166667
accel_air = 0.097222
decel_ground = 0.194444
max_speed_ground = 3.0
max_speed_air = 2.5
turn_resistance = 0.2


[actions.spin]
enabled = false

[actions.fly]
enabled = false

[actions.dash]
enabled = false

[actions.glide]
enabled = false

[actions.spindash]
enabled = false
