version = 1
include = [
  "../../characters/_includes/form_colors_glove_shoe_brown.toml",
  "../../characters/_includes/render_megamanx_placeholder.toml",
  "../../characters/_includes/render_anims_dash_rotate_45.toml",
  "../../characters/_includes/physics_megaman_instant.toml",
  "../../characters/_includes/move_megaman_instant.toml",
  "../../characters/_includes/math_pixel_trunc_256.toml",
  "../../characters/_includes/jump_megaman_impulse_2_33.toml",
  "../../characters/_includes/actions_dash_megaman_press.toml",
]

[name]
id = "test_rise_gravity"
display = "Rise Gravity Test"

[form]
id = "puppet"

[jump]
fall_gravity_multiplier = 1.0
model = "dual_gravity"
rise_gravity_multiplier_held = 0.25
rise_gravity_multiplier_released = 2.5

[actions.spin]
enabled = false

[actions.fly]
enabled = false

[actions.glide]
enabled = false
