version = 1
include = [
  "../../characters/_includes/form_colors_glove_shoe_brown.toml",
  "../../characters/_includes/render_megamanx_placeholder.toml",
  "../../characters/_includes/render_anims_dash_rotate_45.toml",
  "../../characters/_includes/move_megaman_instant.toml",
  "../../characters/_includes/math_pixel_trunc_256.toml",
  "../../characters/_includes/jump_megaman_impulse_2_33.toml",
  "../../characters/_includes/actions_dash_megaman_press.toml",
]

[name]
id = "test_instant_no_air_control"
display = "Mega Man X (Instant, No Air Control)"

[form]
id = "puppet"

[physics]
gravity = 0.0625
max_fall_speed = 5
ground_friction = 8.0
air_drag = 0.0

[move]
air_control = false
[actions.spin]
enabled = false

[actions.fly]
enabled = false

[actions.glide]
enabled = false
