version = 1
include = [
  "../../characters/_includes/form_colors_glove_shoe_brown.toml",
  "../../characters/_includes/render_megamanx_placeholder.toml",
  "../../characters/_includes/render_anims_dash_rotate_45.toml",
  "../../characters/_includes/physics_megaman_instant.toml",
  "../../characters/_includes/move_megaman_instant.toml",
  "../../characters/_includes/math_pixel_trunc_256.toml",
  "../../characters/_includes/jump_megaman_impulse_2_33.toml",
  "../../characters/_includes/actions_dash_megaman_press.toml",
]

[name]
id = "test_wall"
display = "Mega Man X (Wall)"

[form]
id = "puppet"

[actions.wall]
enabled = true
probe = 1.0
slide_gravity_multiplier = 0.35
slide_max_fall_speed = 1.67
jump_impulse = 2.33
jump_vx = 1.50
detach_frames = 18

[actions.spin]
enabled = false

[actions.fly]
enabled = false

[actions.glide]
enabled = false
