version = 1
include = [
  "../../characters/_includes/form_colors_glove_shoe_brown.toml",
  "../../characters/_includes/form_anchor_wario.toml",
  "../../characters/_includes/render_mario_placeholder.toml",
  "../../characters/_includes/physics_wario.toml",
  "../../characters/_includes/move_wario.toml",
  "../../characters/_includes/math_pixel_trunc_16.toml",
  "../../characters/_includes/jump_wario_dual_gravity.toml",
  "../../characters/_includes/actions_dash_wario.toml",
]

[name]
id = "wario_charge"
display = "Wario (Charge)"

[form]
id = "puppet"
palette_base = "FFD700"
palette_accent = "6B2D8B"
variants = ["wario"]

[form.colors]
skin = "FFE4B5"
hat = "FFD700"
overalls = "6B2D8B"
emblem = "FFFFFF"
moustache = "1A1A1A"
button = "FFFFFF"

[actions.spin]
enabled = false

[actions.fly]
enabled = false

[actions.glide]
enabled = false

[actions.spindash]
enabled = false
