version = 1

[stage]
id = "camera_look_torture"
display = "Camera Look Torture"

[world]
width = 2000.0
height = 2000.0

[render]
bg_top = "0C0C10"
bg_bottom = "1A1A28"
platform_base = "4A4A52"
platform_light = "6A6A74"
platform_dark = "2A2A32"
platform_highlight = "8A8A94"

[[solids]]
x = 0.0
y = 700.0
w = 2000.0
h = 80.0

[spawns.default]
x = 120.0
y = 668.0
facing = 1

[camera]
deadzone_w = 0.0
deadzone_h = 0.0
lookahead_x = 0.0
lookahead_y = 0.0
look_hold_ms = 120
look_up_y = 150.0
look_down_y = 150.0

[camera.bounds]
x = 0.0
y = 0.0
w = 2000.0
h = 2000.0

[collision]
ground_snap = 2.0
step_up = 6.0
skin = 0.01
