version = 1

[stage]
id = "camera_lock_torture"
display = "Camera Lock Torture"

[world]
width = 4000.0
height = 600.0

[render]
bg_top = "0C0C10"
bg_bottom = "1A1A28"
platform_base = "4A4A52"
platform_light = "6A6A74"
platform_dark = "2A2A32"
platform_highlight = "8A8A94"

[[solids]]
x = 0.0
y = 500.0
w = 4000.0
h = 80.0

[[solids]]
x = 2700.0
y = 0.0
w = 30.0
h = 600.0

[spawns.default]
x = 1800.0
y = 468.0
facing = 1

[camera]
deadzone_w = 0.0
deadzone_h = 0.0
lookahead_x = 0.0
lookahead_y = 0.0

[[camera.locks]]
x = 1500.0
y = 0.0
w = 1200.0
h = 600.0
bounds_x = 1500.0
bounds_y = 0.0
bounds_w = 1200.0
bounds_h = 540.0

[collision]
ground_snap = 2.0
step_up = 6.0
skin = 0.01
