version = 1

[stage]
id = "hazards_torture"
display = "Hazards Torture"

[world]
width = 600.0
height = 600.0

[render]
bg_top = "0C0C10"
bg_bottom = "1A1A28"
platform_base = "4A4A52"
platform_light = "6A6A74"
platform_dark = "2A2A32"
platform_highlight = "8A8A94"

[[solids]]
x = 0.0
y = 500.0
w = 600.0
h = 80.0

[spawns.default]
x = 120.0
y = 468.0
facing = 1

[[hazards]]
x = 0.0
y = 0.0
w = 200.0
h = 600.0
iframes_ms = 5000
knockback_vx = 6.0
knockback_vy = 0.0

[camera]
deadzone_w = 0.0
deadzone_h = 0.0
lookahead_x = 0.0
lookahead_y = 0.0

[camera.bounds]
x = 0.0
y = 0.0
w = 600.0
h = 540.0

[collision]
ground_snap = 2.0
step_up = 6.0
skin = 0.01
