version = 1

[name]
id = "scout"
display = "Scout Drone"

[stats]
health = 1
score_value = 100
contact_damage = 1.0
invulnerable = false

[collision]
w = 24.0
h = 16.0

[movement]
type = "linear"
velocity_x = -2.0
velocity_y = 0.0

[fire]
type = "none"

[drops]
guaranteed_drop = false

[[drops.entries]]
item_id = "score_small"
probability = 0.3

[[drops.entries]]
item_id = "weapon_upgrade"
probability = 0.05
